### ISSUE TITLE
Screenshot font

### ISSUE THREAD

**Issue by robphoenix** [andradei/theme-minimal-colors#1]
Hi, this theme is just what I was looking for, thanks!

Quick question, what is the font you use in the screenshot?

Thanks.

**Comment by andradei** [comment]
I'm glad you like it!

The font is called Input and is built and downloaded via [this website](http://input.fontbureau.com/)

You can play around with the customization options (I'd recommend you pick "monospace"as one of the options)

It is free of charge **for personal use** (such as developing on your local machine).
